### ISSUE TITLE
memory management

### ISSUE THREAD

**Issue by bAndie91** [sloonz/rewritefs#10]
Hi, I noticed some unhandled `malloc`.
please see my patch, in which all `malloc()` are replaced to `abmalloc()` which simply aborts on memory errors, just like how it is now in most of the places.

https://github.com/bAndie91/rewritefs/commit/354a62dac7943937cc7ec6cc221d8d5704476bd3

cheers.

**Comment by sloonz** [comment]
Should be fixed in master
