### ISSUE TITLE
/g flag

### ISSUE THREAD

**Issue by aude** [sloonz/rewritefs#11]
I would like to use rewritefs to write to a FAT file system.

I'm making a pattern to replace all FAT invalid characters with `_`.

Issue:

```sh
$ echo '/:/ _' > /mnt/home/me/.config/rewritefs
$ mount.fuse rewritefs#/mnt/home/me /home/me -o config=/mnt/home/me/.config/rewritefs,allow_other
$ touch /home/me/foo:
$ ls -l /home/me
total 0
-rw-r--r-- 1 me me 0 Jan 10 12:25 foo_
$ touch /home/me/foo::
$ ls -l /home/me
ls: cannot access '/home/me/foo_:': No such file or directory
total 0
-rw-r--r-- 1 me me 0 Jan 10 12:25 foo_
-????????? ? ?       ?       ?            ? foo_:
```

What do you think about the idea to introduce a `/g` flag?

**Comment by sloonz** [comment]
Implemented in the develop branch

**Comment by aude** [comment]
Consider me impressed.

I'll test it.

**Comment by aude** [comment]
It works well for me. I have successfully used it for copying from ext4 to FAT.

**Comment by sloonz** [comment]
Merged in master
