### ISSUE TITLE
ulockmgr not available in fuse3

### ISSUE THREAD

**Issue by rnhmjoj** [sloonz/rewritefs#12]
Rewritefs can't be built with fuse3 *only* because it needs `ulockmgr.h`, which has been [removed](https://github.com/libfuse/libfuse/commit/3c3f03b81f3027ef0a25bd790605265b384b93c1) from fuse.
This library is supposedly distributed separately, but I can't find in any package besides fuse2: so the README should probably mention that fuse2 is still needed.

**Comment by sloonz** [comment]
Yeah, ulockmgr looks like to be unmaintained. The only point of it was to prevent obtaining two locks on one file (one lock from rewritefs, one lock from the original filesystem). Not worth the hassle, I just removed the ulockmgr dependency and added a warning in the README.
