### ISSUE TITLE
Issue regarding OFD locking

### ISSUE THREAD

**Issue by rnhmjoj** [sloonz/rewritefs#13]
When opening a qemu image under rewritefs, the file lock set by qemu apparently gets stuck.
Launching qemu a second time results in this error:

    qemu-system-x86_64: -drive file=disk.qcow2: Failed to get "write" lock
    Is another process using the image [disk.qcow2]?

Qemu seems to be using OFD locks via the `fcntl` system call. These are traces of the command
`qemu-kvm -drive file=disk.qcow2` running under the plain ext4 fs and rewritefs, obtained via strace:

**ext4**:
```strace
fcntl(10<disk.qcow2>, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=100, l_len=1}) = 0
fcntl(10<disk.qcow2>, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=101, l_len=1}) = 0
fcntl(10<disk.qcow2>, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=103, l_len=1}) = 0
fcntl(10<disk.qcow2>, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=201, l_len=1}) = 0
fcntl(10<disk.qcow2>, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=203, l_len=1}) = 0
fcntl(10<disk.qcow2>, F_OFD_GETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=200, l_len=1, l_pid=0}) = 0
fcntl(10<disk.qcow2>, F_OFD_GETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=201, l_len=1, l_pid=0}) = 0
...
```

**rewritefs**:
```strace
fcntl(10<disk.qcow2>, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=100, l_len=1}) = 0
fcntl(10<disk.qcow2>, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=101, l_len=1}) = 0
fcntl(10<disk.qcow2>, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=103, l_len=1}) = 0
fcntl(10<disk.qcow2>, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=201, l_len=1}) = 0
fcntl(10<disk.qcow2>, F_OFD_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=203, l_len=1}) = 0
fcntl(10<disk.qcow2>, F_OFD_GETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=200, l_len=1, l_pid=0}) = 0
fcntl(10<disk.qcow2>, F_OFD_GETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=201, l_len=1, l_pid=-1}) = 0
...
```

The first difference appears in the last line, where the result indicates there is an OFD read lock at
byte 201 with rewritefs, while with ext4 there are no matching locks.

**Comment by sloonz** [comment]
Can’t manage to reproduce this. It is extra weird since AFAIK the F_OFD_SETLK is not handled by FUSE at all. Can you try with : 

- The last commit which get rids of ulockmgr (I don’t have a lot of hope that it’s related, but you never know)
- With the passthrough_fh.c example of FUSE

?

**Comment by rnhmjoj** [comment]
> The last commit which get rids of ulockmgr (I don’t have a lot of hope that it’s related, but you never know)

Surprisingly, the issue is gone with the latest commit. I tested with the exact same configuration and switching between the old and new version, so I'm pretty sure.
