### ISSUE TITLE
[FEATURE REQUEST] Multiple rewritten paths per rule

### ISSUE THREAD

**Issue by gr3m1in** [sloonz/rewritefs#14]
It would be useful to have an option to specify multiple rewritten paths and e.g. try to stat() them before returning "no such file", just like nginx does with try_files rule.

The use case is to lookup for file at location1/somefile if exists/mounted/accessible and otherwise lookup the same file at location2/somefile, and so on, whatever amount of locations the user specified.

This behavior may be simply skipped if there is only one rewritten path specified, to not affect existing performance for people who doesn't need it.

**Comment by sloonz** [comment]
Thanks for your suggestion. I don't have the time/interest to work on new features for rewritefs for now, but I’m open to a pull request as long as it’s sufficiently simple and don’t penalize the main use case (only 1 location).
