### ISSUE TITLE
Documentation: a small problem

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [sloonz/rewritefs#7]
Hello

You have

> This simple example show how to achieve the same effect than libetc:

That does not make much sense. Do you mean the following?

> This simple example shows you how to achieve the same effect as libetc achieves

i.e. (to use what seems to me a formulation that is better yet):

> The following example demonstrates how one can get the program to do what libetc does.

Also, the reader might wonder what that same effect actually is.

**Comment by sloonz** [comment]
Thank you. My English is unfortunately far from perfect :(
