### ISSUE TITLE
Documentation: add performance overhead estimates

### ISSUE THREAD

**Issue by ngirard** [sloonz/rewritefs#8]
I'm contemplating using rewritefs, but just can't make up my mind because the documentation doesn't tell what performance overhead to expect.

Could you please consider adding this ?

Thanks !

**Comment by sloonz** [comment]
Hello,

I am sorry, but I have no plan to do that. Filesystems benchmarking is a hard and contentious topic ; if you think that performances may be problematic for your use-case, I suggest you to run tests with the specific workload you have in mind.

From my quick, non-rigorous tests : FUSE has an important, non-negligible overhead (you can check this by yourself by testing the passthrough FUSE example ; running tar on my home folder is 5x slower, if my memory serves me right). rewritefs has a pretty-much non-existent overhead relatively to FUSE, but obviously suffers from the overhead of FUSE himself

Cheers

**Comment by ngirard** [comment]
@sloonz, thanks for your answer.

> FUSE has an important, non-negligible overhead (you can check this by yourself by testing the passthrough FUSE example ; running tar on my home folder is 5x slower, if my memory serves me right). rewritefs has a pretty-much non-existent overhead relatively to FUSE, but obviously suffers from the overhead of FUSE himself

Actually, simply adding this piece of information to the README would help a lot, IMHO.
