### ISSUE TITLE
support overmount

### ISSUE THREAD

**Issue by bAndie91** [sloonz/rewritefs#9]
i'd like use rewritefs by mounting over a directory to itself, eg:
```
rewritefs -o config=... ~/dir1 ~/dir1
```
because software writing to ~/dir1 can not be configured to write temporary files elsewhere and the temp files cause heavy IO, but normal files are fine there. and i'd rather don't move underlaying directory's contents, to prevent any software working on normal files from break even if the dir does not get mounted somewhy.

it requires:

- keep file descriptor of the underlying directory open
- and perform underlying fs operations using openat/linkat/fstatat(2) function family taking the saved fd
- allow rewritten path to be out of the source directory

**Comment by sloonz** [comment]
I have a (mostly untested) implementation in the `at` branch, would you mind testing it a bit on your end ?

**Comment by bAndie91** [comment]
hi sloonz, I also developed this feature a while ago - sorry i have not uploaded it earlier. see my branch @development/overmount. I and my family is using this version for 3 months to accelerate web browser (Vivaldi), `~/.config/vivaldi` is overmounted on itself and sqlite journal files are redirected to memory fs. I have not noticed any glitch: no mem-leak, no hanging syscalls. 

There are more changes on my branch, but the one in this scope is commit 12c12c360e.
My approach operates not with `openat()` family functions, but (1) chdir to `orig_fs` and (2) access files by relative path. Because the programm does not chdir elsewhere, the cwd serves like `orig_fd` in your code. I'm not sure which is the better. Yours is more explicite. Mine saves a few calls in `rewrite_opendir` (poorly we dont have `opendirat()` in std lib).

I also removed the constraint which prohibits config file to be under `orig_fs` (recursion loop is avoided by the relative-path feature).

**Comment by bAndie91** [comment]
rewritefs.c#L319

`rewrite_chown()`

`fchownat()` with flags=0 dereferences synlinks, howerver the replaced `lchown()` does not.
I suggest `AT_SYMLINK_NOFOLLOW`.

**Comment by sloonz** [comment]
Good catch on chown/chmod

For *xattr unfortunately there's no way to do that AFAIK. O_NOFOLLOW on openat does not do what you think, it just returns an error if the target is a symlink. 

Your chdir approach can't work with FUSE 3 : libfuse chdir into / at the end of the initialization process. 

I’m going to merge autocreate/at*/abmalloc into develop, do some more polishing, and let it run on my machine for a few days (maybe weeks) before merging into master again.

**Comment by bAndie91** [comment]
hi @sloonz 

1. afaik `chmod` is not affected as there is no `lchmod`

1. regarding to `*xattr`, IMO it should be disallowed on symlinks in order to preserve semantics. (eg. let's do `O_NOFOLLOW` and return error if it fails)

1. chdir-approach

   1. what do you think, does it worth to workaround fuse3 limitation, so do chdir on the first actual call to rewritefs instead to before libfuse initialization? rece condition may be avoided by saving cwd before libfuse and `fchdir` into it later.

    1. my chdir-approach indeed works only in foreground mode

1. note, auto_mkdir feature (239d802c2e5) is not thought through well by me; i committed it to the overmount branch only by lazyness; I'm not fully sure is it a good idea or is it implemented well.

thanks for consideration

**Comment by sloonz** [comment]
Merged in master
